### ISSUE TITLE
Wiki: fix CMake options for mojoshader

### ISSUE THREAD

**Issue by rfht** [FNA-XNA/FNA#199] opened 2018-10-02 17:08 UTC
mojoshader doesn't build with the CMake options that are listed:

```
Parse error in command line argument: -DMOJOSHADER_NO_VERSION_INCLUDE                              
Should be: VAR:type=value
CMake Error: No cmake script provided.
CMake Error: Problem processing arguments. Aborting.
```

Turns out MOJOSHADER_NO_VERSION_INCLUDE is not a CMake option:

```
CMake Warning:
  Manually-specified variables were not used by the project:                                       

    MOJOSHADER_NO_VERSION_INCLUDE
```

The line can still look like this and build with the above warning:

```
-DMOJOSHADER_NO_VERSION_INCLUDE=ON -DBUILD_SHARED=ON -DPROFILE_D3D=OFF -DPROFILE_BYTECODE=OFF -DPROFILE_ARB1=OFF -DPROFILE_ARB1_NV=OFF -DPROFILE_METAL=OFF -DCOMPILER_SUPPORT=OFF -DFLIP_VIEWPORT=ON -DDEPTH_CLIPPING=ON -DXNA4_VERTEXTEXTURE=ON
```

Alternatively, maybe just leave out that option. `README.txt` says:

```
- If you don't have cmake to generate mojoshader_version.h, you can either
  add a blank file with that name, or add MOJOSHADER_NO_VERSION_INCLUDE to
  your preprocessor definitions.
```

**Comment by flibitijibibo** [comment] 2018-10-02 17:10
Can you try this patch? The problem is that the CMake project depends on Hg, which we need to fix in upstream first: https://github.com/FNA-XNA/MojoShader/pull/3

**Comment by flibitijibibo** [comment] 2018-10-02 17:17
Removed the define from the wiki, just need to deal with this Hg problem...

**Comment by flibitijibibo** [comment] 2018-10-05 13:56
The docs are fixed, so I'll close as a sort-of-duplicate of https://github.com/FNA-XNA/MojoShader/pull/3, which needs Ryan's approval first.

**Closed by flibitijibibo** 2018-10-05 13:56 UTC
