### ISSUE TITLE
`IsMouseVisible` does not show mouse cursor on Windows when using FNA.Core

### ISSUE THREAD

**Issue by danielcrenna** [FNA-XNA/FNA#250] opened 2019-04-10 03:43 UTC
Running `FNA.Core` .NET Standard 2.0 in a .NET Core App 2.2 game, on a Windows machine, `IsMouseVisible=true` does not display the mouse cursor.

Repro attached, if you run `Debug|x64` for either project, you see the mouse display for the MonoGame variant, but not for FNA.

[MouseBug.zip](https://github.com/FNA-XNA/FNA/files/3061865/MouseBug.zip)

**Comment by flibitijibibo** [comment] 2019-04-10 03:47
The function call you care about is SDL_ShowCursor:

https://github.com/FNA-XNA/FNA/blob/master/src/FNAPlatform/SDL2_FNAPlatform.cs#L1264

Check to see that this is being called with the correct value and that the native library is using the value as intended. You'll want to build SDL from source and turn on native debugging in VS:

http://libsdl.org/release/SDL2-2.0.9.zip

It should end up around here:

https://hg.libsdl.org/SDL/file/1223f50edde3/src/events/SDL_mouse.c#l1085

**Comment by TheSpydog** [comment] 2019-04-11 22:53
I suspect your submodules are out of date. I linked your sample to the latest version of FNA and manually added the most recent fnalibs distribution to the output directory, and the cursor appeared without issue.

**Comment by flibitijibibo** [comment] 2019-04-20 04:22
Closing due to old age, sounds like it just needs an fnalibs update anyway...

**Closed by flibitijibibo** 2019-04-20 04:22 UTC
