### ISSUE TITLE
Relative mouse mode only working on x axis

### ISSUE THREAD

**Issue by freeeranger** [FNA-XNA/FNA#381] opened 2022-03-03 09:55 UTC
When I enable the relative mouse mode extension it seems that `Mouse.GetState()` returns correct values on the x axis, but it always returns 0 on the y axis. I'm in a very barebones project so I don't think I'm doing anything weird that would cause this.

**Comment by flibitijibibo** [comment] 2022-03-03 13:20
If it's getting one value but not another that might point to something in or below SDL, but without knowing the OS I don't know which file we need to check. Try both Windows and Linux to be sure it's not a high-level issue.

**Comment by freerangerstudios** [comment] 2022-03-03 13:25
I'm on windows 10, unfortunately I don't have a Linux machine at hand and I don't think my computer could handle a virtual machine very well...

I've had issues with SDL relative mouse mode before, so chances are it's an SDL thing.

**Comment by flibitijibibo** [comment] 2022-03-03 14:17
Looks like this is the place to start, blame might have a quick answer: https://github.com/libsdl-org/SDL/blob/main/src/video/windows/SDL_windowsevents.c#L773

**Comment by flibitijibibo** [comment] 2022-03-09 20:47
Possibly relevant: https://github.com/libsdl-org/SDL/pull/5387

**Comment by flibitijibibo** [comment] 2022-03-30 19:08
We're approaching the code freeze for 2.0.22 - I would check the latest Git revision of SDL to see if this is still an issue.

**Comment by TheSpydog** [comment] 2023-12-11 21:40
I can't reproduce this in a minimal sample project on Windows 10 with the latest fnalibs. This has most likely been fixed by SDL at some point over the past ~2 years. If this is still happening for anyone, please report the bug along with a repro project to the SDL issue tracker.

**Closed by TheSpydog** 2023-12-11 21:40 UTC
Labels: SDL2
