### ISSUE TITLE
Nvidia Gsync Performance Drop

### ISSUE THREAD

**Issue by arcooke** [FNA-XNA/FNA#104] opened 2017-03-01 23:35 UTC
I've semi-confirmed this is related to FNA.  

The issue first started happening in Stardew Valley, so I thought it was just an issue with that one game.  Then I bought River City Ransom Underground which also uses FNA ... same exact thing happens.

Both games run at what seems like 3FPS, making it extremely difficult to even navigate main menus to exit.

No other games that I've played (and I have a ton) have this issue, only FNA games.

KDE Neon 
Nvidia driver 375.39 (the issue exists many versions prior)
GTX 970
Acer Predator XB271HU w/ Gsync

To get around this, I have to set up profiles in Nvidia X Server Settings to force Gsync off.  Whether in-game Vsync is on or off has no impact.

![image](https://cloud.githubusercontent.com/assets/6278400/23486256/cd53576a-fea4-11e6-81f3-60cd7f5b37a2.png)

If obtaining a gsync monitor to confirm/debug/test this isn't possible, I'd be happy to try out test samples and report back

**Comment by flibitijibibo** [comment] 2017-03-02 01:50
Stardew Valley's official versions ship with MonoGame rather than FNA, though Maik and I have been experimenting with unofficial FNA versions. So it's probably not that.

The only possible interesting thing we do with vsync is use GLX_EXT_swap_control_tear, but that's a pretty clearly defined OpenGL feature (and if I'm not mistaken NVIDIA were first to implement the feature upon id's request).

Can you check to make sure vsync is turned on for both games? I dunno if Stardew has it, but River City has an option in the graphics settings.

**Comment by flibitijibibo** [comment] 2017-03-02 02:01
I just had a look at MonoGame's source and it appears they don't use swap_control_tear, so you're looking at two separate engines with two different frameworks with two different methods of VSync, all on two different versions of the Mono CLR.

I dunno what the issue is, but something tells me the test pool isn't quite wide enough... you're going to need to profile a bunch of games in the same range first, with either apitrace or RenderDoc (using FNA_OPENGL_FORCE_CORE_PROFILE=1). Here's the FNA game list if you need it:

http://www.flibitijibibo.com/index.php?page=Portfolio/Tools#01_FNA.txt

**Comment by arcooke** [comment] 2017-03-02 02:32
Well then, I guess that shuts down my theory.. ha.  I thought I was onto something.  Thanks.

Do you happen to know of any free XNA games off the top of your head that I can test?  Maybe something from Itch.  Bastion is the only one I have from your list.  Just tested it and it of course works just fine.

**Comment by flibitijibibo** [comment] 2017-03-02 02:36
Here are some free XNA games that can (in theory) be converted with [XnaToFna](https://github.com/0x0ade/XnaToFna):

http://www.bootdiskrevolution.com/free-games/
http://ludumdare.com/compo/ludum-dare-30/?action=preview&uid=1176
http://noelberry.ca/content/games/op/Outpost.zip
http://noelberry.ca/content/games/kiki/KikiAndTheMonster.zip

Also, seems like this has been an issue for you before...?

https://forums.geforce.com/default/topic/974121/-linux-v-sync-and-g-sync-causes-games-to-run-incredibly-bad-like-1-frame-every-3-seconds-is-this-normal-/
http://www.psyonix.com/forum/viewtopic.php?f=34&t=29325&p=304439

Was hard not to bump into you while researching this! (99% of the results seemed to be "X11 makes GSync terrible" for some reason)

**Comment by arcooke** [comment] 2017-03-02 03:06
That's me.   I remember looking for help for this about this with Stardew, but forgot I had issues in others as well.  I guess stardew stuck out in memory because it was the one game that didn't have a vsync option to shut off and had me searching hours/days for a solution.

Apparently nothing's wrong with FNA and my memory is terrible.. sorry to waste your time!   

Thanks for the help :)

**Comment by flibitijibibo** [comment] 2017-03-03 03:25
Closing. Though if you dig into more titles or edit FNA itself to work with G-Sync, go ahead and use this thread to dump patches or whatever.

**Closed by flibitijibibo** 2017-03-03 03:25 UTC
