### ISSUE TITLE
[OS X] With "tap to click" enabled in mouse settings, click presses are inconsistent

### ISSUE THREAD

**Issue by afrodynamics** [FNA-XNA/FNA#130] opened 2017-09-19 21:56 UTC
Received a bug report from a mac user about problems with his trackpad. Turns out FNA has trouble registering "tap to click" events if you have this enabled in system settings. It seems that more than half the time, tap clicks don't fire at all. 

Tap-to-click is an opt-in feature (as far as I'm aware) but there are lots of people (myself included) that swear by it. It makes navigating menus nicer.

I made a blank test project [here](https://github.com/afrodynamics/TapToClickTest).

It's worth playing around with it to get a sense for how often clicks miss. I wanted to report it here first and then escalate it as necessary, if it turns out to be an SDL bug.

**Comment by flibitijibibo** [comment] 2017-09-19 22:19
I just ran a quick test and it appears it's actually not entirely a bug as much as it is XNA's bad Mouse API.

The issue is that Mouse.GetState() is based on the latest MOUSEBUTTON events, so with tap to click what you get is a DOWN event almost immediately followed by an UP event. So it's registering the button just fine, but the tap is so fast that you don't always get the chance to see it.

At one point I considered forcing buttons to be down for a frame if any DOWN event occurred in the frame, but there were accuracy issues involved with that, so we're stuck polling global state for buttons like we do position.

This should fix the issue, and provide far superior mouse input:

https://wiki.libsdl.org/SDL_AddEventWatch
https://wiki.libsdl.org/SDL_Event

```
private static SDL.SDL_EventFilter eventWatcher = SDLEventWatcher;
private static unsafe void SDLEventWatcher(IntPtr func, IntPtr evtPtr)
{
	SDL.SDL_Event* evt = (SDL.SDL_Event*) evtPtr;
	if (evt->type == SDL.SDL_EventType.SDL_MOUSEBUTTONDOWN)
	{
		// Mouse was clicked!
	}
	else if (evt->type == SDL.SDL_EventType.SDL_MOUSEBUTTONUP)
	{
		// Mouse was released!
	}
}

void SomewhereOnStart()
{
	SDL.SDL_AddEventWatch(eventWatcher);
}
```

**Comment by flibitijibibo** [comment] 2017-09-20 01:53
I've been looking at my previous mouse implementations for games where I rewrote the input engine and I think I could introduce an extension without leading to adding a whole events subsystem as an extension (which was my primary reason for not introducing any solution)... it could be called OnClickEXT:

```
// OnClickEXT interaction
private ButtonState[] mouseButtons = new ButtonState[5];
private void OnClick(int button)
{
	mouseButtons[button] = ButtonState.Pressed;
}

// Usual XNA functions...

private MouseState mState = new MouseState();
private MouseState mPrevState;

protected override void Initialize()
{
	Mouse.OnClickEXT += OnClick;

	// Other stuff...

	base.Initialize();
}

protected override void Update(GameTime gameTime)
{
	mPrevState = mState;
	mState = Mouse.GetState();

	// For FNA builds, 'or' the MouseState with the click events!
	ButtonState leftButton = mState.LeftButton | mouseButtons[0];
	ButtonState middleButton = mState.MiddleButton | mouseButtons[1];
	ButtonState rightButton = mState.RightButton | mouseButtons[2];
	ButtonState x1Button = mState.XButton1 | mouseButtons[3];
	ButtonState x2Button = mState.XButton2 | mouseButtons[4];

	// Usual work to get Pressed/Pressing/Release...

	// Other stuff...

	base.Update(gameTime);
}
```

It would still use Mouse.GetState() but would have an additional callback to know for sure that a mouse press occurred. No other event would have a callback, just SDL_MOUSEBUTTONDOWN.

Going to CC @nickgravelyn in since he's the last person I remember that brought this up, though if anyone else has been wondering about this I'd be willing to hear them out on this one.

**Comment by flibitijibibo** [comment] 2017-09-20 17:29
Just added ClickedEXT to master:

https://github.com/FNA-XNA/FNA/commit/76b5264630f00c79d96758d80d326b31050067c8

Documentation:

https://github.com/FNA-XNA/FNA/wiki/5:-FNA-Extensions#clickedext

This works for my use case and is definitely simpler than an AddEventWatch callback if that's all you use it for. Will close this since it resolved this specific issue but feedback is still welcome. If you need something better for 17.10 I need to know within the next 10 days!

**Closed by flibitijibibo** 2017-09-20 17:29 UTC

**Comment by afrodynamics** [comment] 2017-09-20 19:06
This looks like a reasonable solution. I gave the SDL event watch a try yesterday and it was working well. This extension just makes incorporating it a little easier.

Thanks for the quick fix and response!
