### ISSUE TITLE
x64 support?

### ISSUE THREAD

**Issue by xaviergonz** [FNA-XNA/FNA#60] opened 2016-10-02 01:27 UTC
Does this framework support x64?
How does AnyCPU work? does it load different dlls depending on the currently running architecture? (if it works at all)
What about its dll dependencies, are there versions of them all for x64?

I'm talking about Windows in particular btw :)

**Comment by flibitijibibo** [comment] 2016-10-02 01:38
Duplicate of #12; but the short answer is 'build Win64 yourself and for AnyCPU you specify the DLL path with SetDllDirectory.'

**Closed by flibitijibibo** 2016-10-02 01:38 UTC
