### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by kuteninja** [FNA-XNA/FNA#289] opened 2020-01-10 13:23 UTC
This should probably be added to the FAQ later, but I was wondering... Why does FNA have iOS support and no Android? Isn't Android a more "free" environment? I guessed it should be easier to adapt to than iOS which is much more picky overall.

I suppose I could code and build in FNA, and then port to MonoGame or other XNA compatible tool for non-supported devices, but I'd prefer to use just one tool for all releases.

Anyway, you might left this ticket open, so others wandering the same thing know that it's not yet implemented and _why_.

**Comment by flibitijibibo** [comment] 2020-01-10 14:12
Android is a lot like Virtualbox in that it’s living proof that “free” is not the same as “good”:

- Graphics subsystem is absolutely appalling thanks to IHVs who have never ever cared
- Filesystem for developers is a joke and would require ruining our container system that works fine for _literally every other platform including consoles and cloud_
- Keeping up with the NDK is absolutely impossible, even for plain C libraries like ours
- Google will probably [kill it](https://killedbygoogle.com/) after Fuchsia launches anyway, something I would admittedly be very supportive of

I have welcomed developers to try and make a competent Android port for the better part of a decade. Nobody, including some of the smartest developers I know, has come remotely close to making that happen. I will continue welcoming developers to try, not because I expect them to succeed (hence me closing this issue) but because the more people that inevitably fail, the less likely people will mistakenly look back at Android fondly after it finally dies.

**Closed by flibitijibibo** 2020-01-10 14:12 UTC

**Comment by spaceflint7** [comment] 2020-11-15 13:07
I ported FNA to Android as part of my [Bluebonnet](https://github.com/spaceflint7/bluebonnet) project, which is an Android-compatible implementation of .NET on top of the Java Virtual Machine.

I named the port [BNA](https://github.com/spaceflint7/bna) because it isn't an exact port of FNA, and it misses a few key pieces, and I wouldn't want to confuse anyone.  Most of the work I did was rewriting FNA3D and FNAPlatform, almost everything else is exported from `fna.dll` to Java byte code in `bna.jar`.

Even with its incomplete feature set, it might be useful to developers of 2D, or simple 3D games, who want to use FNA, but miss Android support.  Your thoughts please?

**Comment by flibitijibibo** [comment] 2020-11-15 15:38
>  ported FNA to Android as part of my Bluebonnet project

> it isn't an exact port of FNA

Just so we're clear those two don't go well together, and the latter is a _gross_ understatement. You made an FNA lookalike with a very small subset of features that use virtually nothing from FNA itself, including a rewritten platform layer, totally redone 3D layer and Effects format, and no audio engine whatsoever. Nobody using FNA in its current form would get anything out of this, they'd arguably be better off making a whole separate SKU based on MonoGame instead if they were that desperate. You may want to try getting DllImport to work with JNI in Bluebonnet somehow, so that you can use the whole implementation as-is, at least as a starting point.

**Comment by spaceflint7** [comment] 2020-11-15 16:26
> virtually nothing from FNA itself

Not sure I understand this bit.  The [FNA.filter](https://github.com/spaceflint7/bna/blob/master/BNA/FNA.filter) file lists all the classes that I export from FNA into BNA.  This is the bulk of what makes up the resulting `bna.jar`.  Surely all of that counts as FNA?  If not, what then?

> Nobody using FNA in its current form would get anything out of this

I have a simple demo as part of the initial release.  It does sprites and fonts, some basic 3D, render to texture, input with gestures, and XNA storage.  I compile and run it on Windows against the XNA 4 libraries -- no references at all to any Bluebonnet or BNA things.  Then I take these exact same Windows binaries, run them through my Net-to-Java converter, bundle BNA in the same APK, and now it runs on Android.

Say I want to develop a 2D game, I can build against XNA 4, publish to most platforms with FNA, and publish to Android with BNA.  Why do you say this has no value?  Of course, I would need to add missing features like audio.

**Comment by TheSpydog** [comment] 2020-11-15 23:37
@spaceflint7 So, first off, it's obvious that you've put a ton of effort into the .NET CIL -> JVM translation project as well as BNA. Transpiling .NET CIL is a difficult task, and writing a platform layer for Android is a hellish endeavor under the best of circumstances. So kudos for taking on such a challenging project!

I've taken a look at the source for BNA, and I see what you're saying about sharing the bulk of the code with FNA. But I think the issue here is that a partial port of FNA isn't really a port of FNA at all. The core promise of FNA is that every target platform has the exact same FNA.dll, and all the platform-specific stuff is handled in native libraries. That way you're essentially guaranteed that your game logic will operate the exact same way on every supported platform. When you fork the project and completely rewrite the platform/graphics layer, you lose that guarantee.

Beyond that, when you take the "one managed DLL + the native fnalibs" approach to porting FNA, it actually saves you effort since you don't have to implement everything from scratch. You can let SDL2 handle the low-level window, input, and GL setup tasks. FAudio handles audio for you. FNA3D already has a GLES backend (and a full shader translation layer, something that BNA currently lacks). There's a reason we take this approach rather than reimplementing features for each platform.

As flibit mentioned in the reply to the original post, Android presents a bunch of challenges to FNA's single-assembly portability rule. The ideal scenario would be to find a way to remedy these issues in a way that fits with FNA's design philosophy and can be merged upstream.  So if you want to meaningfully contribute to getting upstream FNA running on Android (via Bluebonnet, Xamarin, or whatever), here are some things you can look into:
* Android file system handling via the existing TitleContainer APIs.
* GLES 2.0 support in FNA3D (in a way that doesn't interfere with desktop GL or GLES3 support).
* GL context recovery. Android apps are notorious for discarding their GL context and/or VRAM contents when transitioning between apps and the home screen. We would need an XNA-compliant mechanism for handling this situation.
* Finding a straightforward way to let SDL2 take control of the Activity. (See the [iOS](https://github.com/FNA-XNA/FNA/wiki/Appendix-A:-FNA-on-iOS-and-tvOS#code-changes) and [Xbox One](https://github.com/FNA-XNA/FNA/wiki/Appendix-B:-FNA-on-Consoles#code-differences) sections on the FNA Wiki to see how we handle this on those platforms.)

If these issues prove impossible to solve with upstream FNA, and you absolutely _must_ fork the project to get it running on Android, please at least keep the changes to the bare minimum so you can still get the benefits of upstream bug fixes and improvements. Rewriting the whole platform layer guarantees that you can't stay up-to-date.

Finally, it's worth noting that even if all of these issues are solved and upstream FNA runs perfectly on Android, we're still not going to advertise official support for the platform. There's just way too much device fragmentation and graphics driver craziness to make it worth our while. But there's absolutely nothing stopping unofficial projects like BNA from filling that use case, so long as those projects share FNA's fundamental principles and guarantees.

**Comment by spaceflint7** [comment] 2020-11-16 10:21
> kudos

Thanks, and thank you guys for making FNA.  I started out trying to import the MS XNA libraries, but the design of FNA is much cleaner and better suited for what I needed.

> "one managed DLL + the native fnalibs"

> nothing stopping unofficial projects like BNA from filling that use case, so long as those projects share FNA's fundamental principles and guarantees

I get that FNA implies fnalibs.  But my goal is a system to compile .NET programs to Android with no native code.  Obviously these two things are in conflict -- fnalibs being native code -- so the conflict is probably not resolvable...  Still, BNA is a working implementation of a subset XNA 4, and much of that implementation comes from FNA.

I guess I'm asking how you think I should represent the FNA bits in BNA.  At this time I describe BNA as "a port of FNA for use with Bluebonnet."  If BNA does not meet FNA's fundamental principles and guarantees enough to merit the word 'port', I can tweak the language.

**Comment by flibitijibibo** [comment] 2020-11-16 10:33
> If BNA does not meet FNA's fundamental principles and guarantees enough to merit the word 'port', I can tweak the language.

I can confirm it does not. You're better off stripping all references to the FNA name except in license text where it's mandatory.

**Comment by kuteninja** [comment] 2020-11-16 14:05
@spaceflint7 Just in case, the purpose of this issue was so to have a clearer explanation as to _why_ Android were not supported by FNA and have more visibility of the roadmap, in case it were viable on a near future, but I'm not looking for an alternative product at the moment.

I know that the project could be ported to Monogame which is compatible (up to a certain degree) with FNA and then export to Android, but it's mostly a workaround since you lose the XNA compatibility and some unknown bugs could emerge due to these drifts.

**Comment by spaceflint7** [comment] 2020-11-16 20:32
I get that FNA means 100% compatibility with XNA, and clearly there is concern here that my fork might tarnish that, and I respect that.  I can't just _hide_ that I use FNA -- it's part of the build process -- but I will revise the description to address your concerns.

**Comment by matteoturini** [comment] 2022-02-06 06:15
> after it finally dies.

it won't anytime soon

**Comment by srodrigo** [comment] 2023-04-22 08:40
> it won't anytime soon

Yeah, there are literally BILLIONS of Android devices, so I'm not sure how it's going to die in the next 10 years. Also, I'm not sure how close Fuchsia is from being viable commercially on Android. It's been 7 years already and I'm not sure when it'll become an actual thing apart from a few Google devices here and there. Also, while it's getting new releases and looks like it's in active development, it does NOT look good at all: https://arstechnica.com/gadgets/2023/01/big-layoffs-at-googles-fuchsia-os-call-the-projects-future-into-question/ - I very much doubt this project will ever replace Android. Not to mention the millions of applications that would need to be (sup)ported.

I've never tried porting anything to Android, so I trust that it's not trivial at all. Yet, there are many frameworks of all sorts (specially game frameworks/engines) that support Android. Maybe they have more people-power to keep up, but it's definitely doable.

I'm afraid this is my showstopper for considering FNA instead of MonoGame, as I like being able to port to Android. Thanks for your honesty and hard work though!

**Comment by thatcosmonaut** [comment] 2023-04-25 20:50
We have made our stance on Android support extremely clear. Any further discussion of this is pointless.
