### ISSUE TITLE
Effect and floating precision

### ISSUE THREAD

**Issue by andreakarasho** [FNA-XNA/FNA#231] opened 2019-01-16 15:02 UTC
Hi i spent last 5h to understand why my shader didn't work and i found this issue:

Into my sbritebatch constructor: 

https://github.com/andreakarasho/ClassicUO/blob/6303d9440bd548b4b79ecb1d588ec3b65eb825f3/src/Renderer/Batcher2D.cs#L69
(HuesCount = 3000)

my shader:
https://github.com/andreakarasho/ClassicUO/blob/6303d9440bd548b4b79ecb1d588ec3b65eb825f3/src/shaders/IsometricWorld.fx#L79

my game sends to shader the color 2822 (stored into IN.Hue.x), but into my game i saw the previous color (2821).
After changed the HuesPerTexture to 3000.0f and nothing else, i can see the color 2822 correctly.

Is there a loss precision point when i pass data from C# to shader?

edit:
i tried to declare into my shader:
```
const float huesCount = 3000.0f;
```
but doesn't work. I have to do:
```if (IN.Hue.x < HuesPerTexture)
			color.rgb = tex2D(HueSampler0, float2(color.r, IN.Hue.x / 3000.0f)).rgb;
		else
			color.rgb = tex2D(HueSampler1, float2(color.r, (IN.Hue.x - 3000.0f) / 3000.0f)).rgb;
```

**Comment by flibitijibibo** [comment] 2019-01-16 16:13
Take the half pixel offset out of the vertex shader (and the rest of your engine) and see if that fixes it.

**Comment by andreakarasho** [comment] 2019-01-17 08:31
I think you meant those lines:
https://github.com/andreakarasho/ClassicUO/blob/6303d9440bd548b4b79ecb1d588ec3b65eb825f3/src/shaders/IsometricWorld.fx#L55

if i remove them:
- horrible graphic
- no fix the problem

**Comment by flibitijibibo** [comment] 2019-01-17 15:13
It sounds like you have random precision problems all throughout then - in isolation this works for me but stuff like the half-pixel offset is usually why things break (D3D9 needs it but all other APIs do not). Look at the fxc disassembly and MojoShader GLSL output to get an idea of what values are being stored and how everything is getting put together; in particular there are lots of branches in the HLSL but the asm just does all the branches at once, which can lead to lots of unintended consequences:

https://plus.google.com/+flibitijibibo/posts/MnHMGCwiLbe

**Comment by flibitijibibo** [comment] 2019-01-17 15:24
Here’s another half-pixel offset, for example:

https://github.com/andreakarasho/ClassicUO/blob/6303d9440bd548b4b79ecb1d588ec3b65eb825f3/src/Renderer/Batcher2D.cs#L518

**Comment by flibitijibibo** [comment] 2019-01-17 16:51
Here's the asm of your pixel shader:

```
        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
            //
            // Parameters:
            //
            //   float HuesPerTexture;
            //   float3 lightDirection;
            //
            //
            // Registers:
            //
            //   Name           Reg   Size
            //   -------------- ----- ----
            //   HuesPerTexture c0       1
            //   lightDirection c1       1
            //
            
                preshader
                rcp c0.x, c0.x
                dot r0.xyz, c1.xyz, c1.xyz
                rsq r1.x, r0.x
                mul c1.xyz, r1.x, c1.xyz
            
            // approximately 4 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
            //
            // Parameters:
            //
            //   bool DrawLighting;
            //   sampler2D DrawSampler;
            //   sampler2D HueSampler0;
            //   sampler2D HueSampler1;
            //   float HuesPerTexture;
            //   float lightIntensity;
            //
            //
            // Registers:
            //
            //   Name           Reg   Size
            //   -------------- ----- ----
            //   HuesPerTexture c2       1
            //   DrawLighting   c3       1
            //   lightIntensity c4       1
            //   DrawSampler    s0       1
            //   HueSampler0    s1       1
            //   HueSampler1    s2       1
            //
            
                ps_2_0
                def c5, -2, -6, 0.5, -7
                def c6, -10, 1.5, 1, 0
                def c7, -1, -0, 0, 1
                dcl t0.xy
                dcl t1.xyz
                dcl t2.xyz
                dcl_2d s0
                dcl_2d s1
                dcl_2d s2
                texld r0, t0, s0
                cmp r1, -r0.w, c7.x, c7.y
                texkill r1
                add r1.x, -r0.z, r0.x
                mul r1.x, r1.x, r1.x
                cmp r1.x, -r1.x, c7.x, c7.y
                add r1.y, -r0.y, r0.x
                mul r1.y, r1.y, r1.y
                cmp r1.x, -r1.y, r1.x, c7.y
                mov r2.xyz, r0
                frc r1.y, t2.y
                cmp r1.z, -r1.y, c7.z, c7.w
                cmp r1.z, t2.y, c7.z, r1.z
                add r1.y, -r1.y, t2.y
                add r1.y, r1.z, r1.y
                add r1.z, r1.y, c6.x
                mul r1.z, r1.z, r1.z
                add r1.w, r1.y, c7.x
                mul r1.w, r1.w, r1.w
                mov r3.x, r0.x
                mov r4.x, r3.x
                mul r3.y, t2.x, c0.x
                add r3.z, t2.x, -c2.x
                mul r4.y, r3.z, c0.x
                texld r4, r4, s2
                texld r5, r3, s1
                cmp r3.xyz, r3.z, r4, r5
                add r4.x, r1.y, c5.x
                add r4.y, r1.y, c5.y
                mul r4.xy, r4, r4
                add r1.y, r1.y, c5.w
                mul r1.y, r1.y, r1.y
                mad r5.w, r0.x, -c6.y, c6.z
                add r2.w, -t2.z, c7.w
                mov r5.xyz, c7.z
                cmp r2, -r1.z, r5, r2
                nrm r5.xyz, t1
                dp3 r1.z, r5, c1
                add r1.z, r1.z, c5.z
                max r4.z, r1.z, c7.z
                add r5.w, -t2.z, c7.w
                mul r5.xyz, r3, r4.z
                cmp r2, -r1.y, r5, r2
                add r5.w, -t2.z, c7.w
                mul r5.xyz, r0, r4.z
                cmp r2, -r4.y, r5, r2
                add r5.w, -t2.z, c7.w
                cmp r5.xyz, r1.x, r0, r3
                cmp r2, -r4.x, r5, r2
                add r3.w, -t2.z, c7.w
                cmp r1, -r1.w, r3, r2
                mul r2.xyz, r1, c4.x
                cmp r0.xyz, -c3.x, r1, r2
                mul r0, r1.w, r0
                mov oC0, r0
            
            // approximately 57 instruction slots used (3 texture, 54 arithmetic)
            };
```

And here's the GLSL:

```
    OBJECT #2: SHADER, technique 0, pass 0
        PROFILE: glsl
        SHADER TYPE: pixel
        VERSION: 2.0
        INSTRUCTION COUNT: 58
        MAIN FUNCTION: ShaderFunction2
        INPUTS: (none.)
        OUTPUTS:
            * (null) ("ps_oC0")
        CONSTANTS:
            * 5: float (-2.000000 -6.000000 0.500000 -7.000000)
            * 6: float (-10.000000 1.500000 1.000000 0.000000)
            * 7: float (-1.000000 -0.000000 0.000000 1.000000)
        UNIFORMS:
            * 0: float ("ps_c0")
            * 1: float ("ps_c1")
            * 2: float ("ps_c2")
            * 3: float ("ps_c3")
            * 4: float ("ps_c4")
        SAMPLERS:
            * 0: 2d ("ps_s0")
            * 1: 2d ("ps_s1")
            * 2: 2d ("ps_s2")
        SYMBOLS:
            * 0: "DrawLighting"
              register set float4
              register index 3
              register count 1
              symbol class scalar
              symbol type bool
              rows 1
              columns 1
              elements 1
            * 1: "DrawSampler"
              register set sampler
              register index 0
              register count 1
              symbol class object
              symbol type sampler2d
              rows 1
              columns 1
              elements 1
            * 2: "HueSampler0"
              register set sampler
              register index 1
              register count 1
              symbol class object
              symbol type sampler2d
              rows 1
              columns 1
              elements 1
            * 3: "HueSampler1"
              register set sampler
              register index 2
              register count 1
              symbol class object
              symbol type sampler2d
              rows 1
              columns 1
              elements 1
            * 4: "HuesPerTexture"
              register set float4
              register index 2
              register count 1
              symbol class scalar
              symbol type float
              rows 1
              columns 1
              elements 1
            * 5: "lightIntensity"
              register set float4
              register index 4
              register count 1
              symbol class scalar
              symbol type float
              rows 1
              columns 1
              elements 1

        PRESHADER:
            SYMBOLS:
                * 0: "HuesPerTexture"
                  register set float4
                  register index 0
                  register count 1
                  symbol class scalar
                  symbol type float
                  rows 1
                  columns 1
                  elements 1
                * 1: "lightDirection"
                  register set float4
                  register index 1
                  register count 1
                  symbol class vector
                  symbol type float
                  rows 1
                  columns 3
                  elements 1

            rcp c0.x, c0.x
            dot r0.xyz, c1.xyz, c1.xyz
            rsq r1.x, r0.x
            mul c1.xyz, r1.x, c1.xyz

        OUTPUT:
            #version 120
            uniform vec4 ps_uniforms_vec4[5];
            const vec4 ps_c5 = vec4(-2.0, -6.0, 0.5, -7.0);
            const vec4 ps_c6 = vec4(-10.0, 1.5, 1.0, 0.0);
            const vec4 ps_c7 = vec4(-1.0, 0.0, 0.0, 1.0);
            vec4 ps_r0;
            vec4 ps_r1;
            vec4 ps_r2;
            vec4 ps_r3;
            vec4 ps_r4;
            vec4 ps_r5;
            #define ps_c0 ps_uniforms_vec4[0]
            #define ps_c1 ps_uniforms_vec4[1]
            #define ps_c2 ps_uniforms_vec4[2]
            #define ps_c3 ps_uniforms_vec4[3]
            #define ps_c4 ps_uniforms_vec4[4]
            uniform sampler2D ps_s0;
            uniform sampler2D ps_s1;
            uniform sampler2D ps_s2;
            #define ps_t0 gl_TexCoord[0]
            #define ps_t1 gl_TexCoord[1]
            #define ps_t2 gl_TexCoord[2]
            #define ps_oC0 gl_FragColor
            
            void main()
            {
            	ps_r0 = texture2D(ps_s0, ps_t0.xy);
            	ps_r1 = ((-ps_r0.w >= 0.0) ? ps_c7.xxxx : ps_c7.yyyy);
            	if (any(lessThan(ps_r1.xyz, vec3(0.0)))) discard;
            	ps_r1.x = -ps_r0.z + ps_r0.x;
            	ps_r1.x = ps_r1.x * ps_r1.x;
            	ps_r1.x = ((-ps_r1.x >= 0.0) ? ps_c7.x : ps_c7.y);
            	ps_r1.y = -ps_r0.y + ps_r0.x;
            	ps_r1.y = ps_r1.y * ps_r1.y;
            	ps_r1.x = ((-ps_r1.y >= 0.0) ? ps_r1.x : ps_c7.y);
            	ps_r2.xyz = ps_r0.xyz;
            	ps_r1.y = fract(ps_t2.y);
            	ps_r1.z = ((-ps_r1.y >= 0.0) ? ps_c7.z : ps_c7.w);
            	ps_r1.z = ((ps_t2.y >= 0.0) ? ps_c7.z : ps_r1.z);
            	ps_r1.y = -ps_r1.y + ps_t2.y;
            	ps_r1.y = ps_r1.z + ps_r1.y;
            	ps_r1.z = ps_r1.y + ps_c6.x;
            	ps_r1.z = ps_r1.z * ps_r1.z;
            	ps_r1.w = ps_r1.y + ps_c7.x;
            	ps_r1.w = ps_r1.w * ps_r1.w;
            	ps_r3.x = ps_r0.x;
            	ps_r4.x = ps_r3.x;
            	ps_r3.y = ps_t2.x * ps_c0.x;
            	ps_r3.z = ps_t2.x + -ps_c2.x;
            	ps_r4.y = ps_r3.z * ps_c0.x;
            	ps_r4 = texture2D(ps_s2, ps_r4.xy);
            	ps_r5 = texture2D(ps_s1, ps_r3.xy);
            	ps_r3.xyz = ((ps_r3.z >= 0.0) ? ps_r4.xyz : ps_r5.xyz);
            	ps_r4.x = ps_r1.y + ps_c5.x;
            	ps_r4.y = ps_r1.y + ps_c5.y;
            	ps_r4.xy = ps_r4.xy * ps_r4.xy;
            	ps_r1.y = ps_r1.y + ps_c5.w;
            	ps_r1.y = ps_r1.y * ps_r1.y;
            	ps_r5.w = (ps_r0.x * -ps_c6.y) + ps_c6.z;
            	ps_r2.w = -ps_t2.z + ps_c7.w;
            	ps_r5.xyz = ps_c7.zzz;
            	ps_r2 = ((-ps_r1.z >= 0.0) ? ps_r5 : ps_r2);
            	ps_r5.xyz = normalize(ps_t1.xyz);
            	ps_r1.z = dot(ps_r5.xyz, ps_c1.xyz);
            	ps_r1.z = ps_r1.z + ps_c5.z;
            	ps_r4.z = max(ps_r1.z, ps_c7.z);
            	ps_r5.w = -ps_t2.z + ps_c7.w;
            	ps_r5.xyz = ps_r3.xyz * ps_r4.zzz;
            	ps_r2 = ((-ps_r1.y >= 0.0) ? ps_r5 : ps_r2);
            	ps_r5.w = -ps_t2.z + ps_c7.w;
            	ps_r5.xyz = ps_r0.xyz * ps_r4.zzz;
            	ps_r2 = ((-ps_r4.y >= 0.0) ? ps_r5 : ps_r2);
            	ps_r5.w = -ps_t2.z + ps_c7.w;
            	ps_r5.xyz = ((ps_r1.x >= 0.0) ? ps_r0.xyz : ps_r3.xyz);
            	ps_r2 = ((-ps_r4.x >= 0.0) ? ps_r5 : ps_r2);
            	ps_r3.w = -ps_t2.z + ps_c7.w;
            	ps_r1 = ((-ps_r1.w >= 0.0) ? ps_r3 : ps_r2);
            	ps_r2.xyz = ps_r1.xyz * ps_c4.xxx;
            	ps_r0.xyz = ((-ps_c3.x >= 0.0) ? ps_r1.xyz : ps_r2.xyz);
            	ps_r0 = ps_r1.wwww * ps_r0;
            	ps_oC0 = ps_r0;
            }
```

If there's a problem with the generated output I'm not seeing it.

**Comment by andreakarasho** [comment] 2019-01-17 20:56
i think the problem is inside the C# core code.
here: https://github.com/andreakarasho/ClassicUO/blob/6303d9440bd548b4b79ecb1d588ec3b65eb825f3/src/Renderer/Batcher2D.cs#L69

.SetValue(A_FLOAT_VALUE) seems doesn't work properly. It seems like set an Integer (i'm not able to verify this, but a float value doesn't work )

**Comment by flibitijibibo** [comment] 2019-01-17 22:55
Note that if you send the plain integer value, it simply gets cast based on the effect parameter type:

https://github.com/FNA-XNA/FNA/blob/master/src/Graphics/Effect/EffectParameter.cs#L523

In addition to removing the half pixel offsets, try to optimize and de-branch the shader so that the asm is more representative of what the HLSL is actually doing, and doesn't have the preshader on start. The less there is for the compiler to optimize, the more stable (and faster!) it will be.

Going to close this because I keep looking at the GLSL and it is byte-for-byte the same, and the issue is likely due to precision out of FNA's control.

**Closed by flibitijibibo** 2019-01-17 22:55 UTC
