### ISSUE TITLE
Texture2D.FromStream always crach

### ISSUE THREAD

**Issue by oldteen** [FNA-XNA/FNA#141] opened 2017-11-16 12:07 UTC
Hello,

Here a piece of code:
```
var path = @"V:\Dropbox\BlackBones\Projects\DwarfCore\DCTest\res\textures\images.png";
var texture = Microsoft.Xna.Framework.Graphics.Texture2D.FromStream(Device, System.IO.File.OpenRead(path));
```
The Texture2D.FromStream always crash. Apparently SDL2_Image cannot load the image.

The problem seems to come from the function TextureDataFromStream in SDL2_FNAPlatform
All are ok until this line : `IntPtr surface = SDL_image.IMG_Load_RW(rwops, 1);`
IMG_Load_RW return a null pointer

I use the version of FNA 17.11 and the last archive of dll. I use .NetCore 2 and the archi x64

Any idea ?
Thanks,
Thierry

**Comment by flibitijibibo** [comment] 2017-11-16 13:07
I need either an image file or a native trace. Preferably both.

**Comment by flibitijibibo** [comment] 2017-11-16 15:31
Added a LogError for IMG_Load_RW failing but I will still need something to test:

https://github.com/FNA-XNA/FNA/commit/69cf4efdb2c7aa86b12bac56559fe8897997fe68

**Comment by oldteen** [comment] 2017-11-17 17:18
with your log :
`TextureDataFromStream: Failed loading libpng16-16.dll: Le module spécifié est introuvable.`

I have checked libpng16-16.dll and it's in the same place as SDL2_image.dll or SDL2.dll. I will try with another version. I have already tester with dll in your x86 or x64 package.

If I delete libpng16-16.dll I've got the same error.

I will look for native trace

Thanks for your help,
Thierry

**Comment by flibitijibibo** [comment] 2017-11-17 17:22
Are all the dlls matching architectures? I can't reproduce this locally.

**Comment by oldteen** [comment] 2017-11-17 17:26
FNA.core use x64 and my project x64 too and I take the x64 package of dll.
I will try with a new project (without .netcore)

**Comment by flibitijibibo** [comment] 2017-11-17 17:28
Also, be sure you have zlib1.dll in the output folder as well.

**Comment by oldteen** [comment] 2017-11-17 18:47
I've made more tests. I've got the problem only with .NetCore. With framework 4/4.5 no problem :)

**Comment by flibitijibibo** [comment] 2017-11-17 19:23
Hm, tell you what: Let's funnel this into the UWP support thread for SDL2#:

https://github.com/flibitijibibo/SDL2-CS/issues/114

I need to figure out UWP compilation for SDL_image anyhow...

Closing in favor of the above issue.

**Closed by flibitijibibo** 2017-11-17 19:23 UTC

**Comment by oldteen** [comment] 2017-11-17 19:25
ok :)
I can do my things with standard .net
Thanks

**Comment by flibitijibibo** [comment] 2017-11-22 01:15
I just pushed an update to fnalibs, can you try this again with the latest, making sure that the DLLs are all copied to the output?

**Comment by smack0007** [comment] 2017-11-22 07:25
Does the problem exist with this specific png file or is it any png file? I can successfully load a png file on .NET Core in 64 bit. I'm loading all the unmanaged DLLs at program load time though.

**Comment by flibitijibibo** [comment] 2017-11-22 13:55
I think it was just a bad DLL. If it works, great!

**Comment by sherjilozair** [comment] 2018-05-06 22:57
@flibitijibibo Hi Ethan, I get a similar error in macos. The SDL dylib gets read fine, but somehow libSDL2_image does not.

This is the trace:

```
System.DllNotFoundException: libSDL2_image-2.0.0.dylib
  at at (wrapper managed-to-native) SDL2.SDL_image.IMG_Load_RW(intptr,int)
  at Microsoft.Xna.Framework.SDL2_FNAPlatform.TextureDataFromStream (System.IO.Stream stream, System.Int32& width, System.Int32& height, System.Byte[]& pixels, System.Int32 reqWidth, System.Int32 reqHeight, System.Boolean zoom) [0x0000f] in /Users/sherjilozair/Downloads/FNA/src/FNAPlatform/SDL2_FNAPlatform.cs:1157
  at Microsoft.Xna.Framework.Graphics.Texture2D.TextureDataFromStreamEXT (System.IO.Stream stream, System.Int32& width, System.Int32& height, System.Byte[]& pixels, System.Int32 requestedWidth, System.Int32 requestedHeight, System.Boolean zoom) [0x00010] in /Users/sherjilozair/Downloads/FNA/src/Graphics/Texture2D.cs:375
  at Microsoft.Xna.Framework.Graphics.Texture2D.FromStream (Microsoft.Xna.Framework.Graphics.GraphicsDevice graphicsDevice, System.IO.Stream stream) [0x0000b] in /Users/sherjilozair/Downloads/FNA/src/Graphics/Texture2D.cs:305
  at FNATestProject.TestGame.LoadContent () [0x0001d] in /Users/sherjilozair/Projects/FNATestProject/FNATestProject/TestGame.cs:35
  at Microsoft.Xna.Framework.Game.Initialize () [0x00064] in /Users/sherjilozair/Downloads/FNA/src/Game.cs:731
  at FNATestProject.TestGame.Initialize () [0x00001] in /Users/sherjilozair/Projects/FNATestProject/FNATestProject/TestGame.cs:28
  at Microsoft.Xna.Framework.Game.DoInitialize () [0x0000f] in /Users/sherjilozair/Downloads/FNA/src/Game.cs:842
  at Microsoft.Xna.Framework.Game.Run () [0x00014] in /Users/sherjilozair/Downloads/FNA/src/Game.cs:418
  at FNATestProject.Program.Main (System.String[] args) [0x00008] in /Users/sherjilozair/Projects/FNATestProject/FNATestProject/Program.cs:11
```

**Comment by mklingen** [comment] 2018-08-25 21:05
@flibitijibibo my players are reporting similar issues with `libSDL2_image` not getting found, using the latest libSDL2_image dylib from FNALibs.

**Comment by flibitijibibo** [comment] 2018-08-25 22:27
Double checking the `otool` output, the best I can guess is that the libpng/libjpeg dependencies aren't there! This was admittedly a recent change (by recent I mean mid 2017), but an upcoming change that might fix this is SDL_image_compact:

https://github.com/FNA-XNA/SDL_image_compact

If you can `make` this project, great, if not, I'll be making official builds after FNA 18.09 alongside the other upcoming fnalibs updates. Send reports if the build isn't building!

**Comment by mklingen** [comment] 2018-08-26 20:28
I think my issue was in just not understanding where `osx` dylibs should be exported. Turns out they need to be in a folder called `osx` relative to the executable, rather than loose right next to it.
