### ISSUE TITLE
RT readback introduces vsync stalls (on NVIDIA/Windows?)

### ISSUE THREAD

**Issue by kg** [FNA-XNA/FNA#258] opened 2019-06-22 05:29 UTC
I have a set of RenderTarget2Ds I rotate through and then call GetData on to read back the result of rendering operations. GetData operations usually (occasionally don't for no obvious reason) block until vsync under these circumstances, while they take about 0.5ms under windows d3d9 XNA.

I tried lots of stuff and have come up with exactly one workaround: If it's blocking on vsync, what if I get rid of vsync?

```csharp
                SDL2.SDL.SDL_GL_SetSwapInterval(0);
                instance?.GetData(buffer);
                SDL2.SDL.SDL_GL_SetSwapInterval(-1);
```

Occasionally I don't seem to get a Cursed Context at startup and the GetData calls are speedy without doing this, so it seems to be something weird in the GL ICD. It's more likely to work right in Release builds of FNA. Forcing the core context (or compatibility context) seems to have no impact.

EDIT: Also, this applies to both forms of readback - glReadPixels from an RT while it's bound, and reading via glGetTextureSubImage.

**Comment by flibitijibibo** [comment] 2019-12-26 16:21
Do we still want to keep this issue filed? It seems like one of those things that will just be open indefinitely since the issue is with the ICD, and I doubt they'll listen to any of us... we can probably have this as a checkbox under the VulkanDevice work.

**Comment by kg** [comment] 2019-12-26 20:44
Yeah, seems worthwhile to just keep this in mind for vulkandevice. I'd still love to test this for ANGLE but ANGLE still doesn't work for me...

**Comment by flibitijibibo** [comment] 2020-04-10 15:55
We're going to be moving to FNA3D's issue tracker for graphics issues. At the same time, D3D11Renderer is now in development. If this is still an issue when FNA3D releases officially, re-file over at the new tracker!

**Closed by flibitijibibo** 2020-04-10 15:55 UTC
