### ISSUE TITLE
register swaps in effects

### ISSUE THREAD

**Issue by electroholic** [FNA-XNA/FNA#333] opened 2020-10-08 08:30 UTC
Hi

First, thanks for the work you do on this. It's a been a breeze moving from XNA to FNA so far. One niggle though (which I guess is maybe actually an issue with Mojo).

I use a bunch of postprocessing effects on my game and when I run everything through an FNA build I think mojo reverses the sampler register indexes in a bloom combine effect I use.

Took me a while to figure out what was happening and have had to basically reverse the render targets around to handle it but thought I should mention the issue.

**Comment by flibitijibibo** [comment] 2020-10-08 12:07
Here's where samplers are updated:

https://github.com/FNA-XNA/FNA/blob/master/src/Graphics/Effect/Effect.cs#L671

If it's BloomComponent we're looking at, that's been known to work since ~2013, so I'd like to have a test program to verify anything that's not well-known sample code.

**Comment by flibitijibibo** [comment] 2020-10-08 12:45
More info... the sampler declaration:

https://github.com/FNA-XNA/MojoShader/blob/upstream/mojoshader.c#L1300

Note that we have a regnum at this point - the compiled effect will always have register index values by the end of compilation, whether it's explicitly named or not, so we're just using what the application gives us. MojoShader not parsing sampler registers correctly would break pretty much every program in the entire catalog. Unspecified sampler registers are, as you might expect, undefined, and can change between FXC versions (including XNA <-> FXC).

**Comment by electroholic** [comment] 2020-10-08 21:38
weird.

I'm going to have to double check. cheers for the pointers to the source.

**Comment by electroholic** [comment] 2020-10-09 08:28
Hi

Hope you don't mind a bunch of pngs to illustrate the steps I sent through - and it's even weirder (not sure what I've done in my postprocess pipeline to cause it but its repeatable and predictable).

So in XNA the final render is like xna.png

Unchanged in FNA I get FNA_no_code_change.png (basically looks like the combine has used only the gaussian blur and not the base image)

If I flip the render targets around I get FNA_reverse_render_targets.png.

Finally if I edit the fx file to reverse the registers and also leave the render targets swapped around I get FNA_reverse_render_targets_and_registers.png.

So I can only get like for like if I swap things around in both the fx file and the reverse the render targets.

![FNA_no_code_change](https://user-images.githubusercontent.com/55522/95560913-d3426e00-0a11-11eb-93f9-d9da5215bd1a.png)
![FNA_reverse_render_targets](https://user-images.githubusercontent.com/55522/95560914-d3db0480-0a11-11eb-965a-425a668a4628.png)
![FNA_reverse_render_targets_and_registers](https://user-images.githubusercontent.com/55522/95560917-d4739b00-0a11-11eb-8799-d515d5a6b40d.png)
![xna](https://user-images.githubusercontent.com/55522/95560919-d4739b00-0a11-11eb-9b2c-09e32c6cbd72.png)

**Comment by flibitijibibo** [comment] 2020-10-09 13:43
What exactly does this fx file look like?

**Comment by electroholic** [comment] 2020-10-09 14:53
this is the original before I flip the registers

`sampler BloomSampler : register(s0);
sampler BaseSampler : register(s1);

float BloomIntensity;
float BaseIntensity;

float BloomSaturation;
float BaseSaturation;


// Helper for modifying the saturation of a color.
float4 AdjustSaturation(float4 color, float saturation)
{
    // The constants 0.3, 0.59, and 0.11 are chosen because the
    // human eye is more sensitive to green light, and less to blue.
    float grey = dot(color, float3(0.3, 0.59, 0.11));

    return lerp(grey, color, saturation);
}


float4 PixelShaderFunction(float2 texCoord : TEXCOORD0) : COLOR0
{
    // Look up the bloom and original base image colors.
    float4 bloom = tex2D(BloomSampler, texCoord);
    float4 base = tex2D(BaseSampler, texCoord);
    
    // Adjust color saturation and intensity.
    bloom = AdjustSaturation(bloom, BloomSaturation) * BloomIntensity;
    base = AdjustSaturation(base, BaseSaturation) * BaseIntensity;
    
    // Darken down the base image in areas where there is a lot of bloom,
    // to prevent things looking excessively burned-out.
    base *= (1 - saturate(bloom));
    
    // Combine the two images.
    return base + bloom;
}


technique BloomCombine
{
    pass Pass1
    {
        PixelShader = compile ps_2_0 PixelShaderFunction();
    }
}`

**Comment by flibitijibibo** [comment] 2020-10-09 15:36
Right, so we're definitely looking at BloomComponent (which I hope has not been modified). I will need to see a full build to verify that the right version is being used, as we've used this dozens of times in the past with no issues.

**Comment by electroholic** [comment] 2020-10-09 16:23
Its pretty heavily modified around the bloom code but then that code itself is left pretty much vanilla (it just switches between a scanlines effect and a combined scanlines and shock wave effect prior to running the bloom, so its basically just run a post process eftect into the render target that gets used as the base image for the bloom code already)

unfortunately providing a full build is tricky as its a full game already.

I can live with the workaround I stumnbled on tbh. but was just a bit baffled as to the difference in behaviour.

**Comment by flibitijibibo** [comment] 2020-10-09 16:42
An apitrace and RenderDoc capture of both builds would also work:

http://apitrace.github.io/
https://renderdoc.org/

**Comment by electroholic** [comment] 2020-10-09 16:50
I'll see what I can grab over the weekend. cheers again. I'll drop an update here when I have traces from both builds for you.

**Comment by electroholic** [comment] 2020-10-11 09:41
Have attached an archive with 2 api trace files. the fna trace is producing output as in the second png I posted (looking like its just using the gaussian blur only when combining), the xna trace file is working normally. this is the unchanged fx and draw call scenario.

cheers


[apitraces.zip](https://github.com/FNA-XNA/FNA/files/5360866/apitraces.zip)

**Comment by flibitijibibo** [comment] 2020-10-11 18:41
Found something really peculiar in the trace... can you disable mipmaps in your RenderTarget2D constructors? Also, try passing `/gldevice:OpenGL` as a launch argument.

**Comment by electroholic** [comment] 2020-10-11 19:59
hey - works in open gl - trace attached (removed the mipmap true args in the rendertarget constructor calls also) - can confirm that this didn't fix the d3d11 renderer btw.

[Smatter_FNA_GL.zip](https://github.com/FNA-XNA/FNA/files/5361871/Smatter_FNA_GL.zip)

**Comment by flibitijibibo** [comment] 2020-10-11 19:59
Some more odd behavior: The targets appear to be half-size under D3D11, which explains the blurring that I'm seeing... aside from that the traces actually look the same to me at the Press Start screen. I don't think the issue is with the shaders, it might be the render targets in general. Are you using something like the GraphicsProfile to choose target behavior?

**Comment by flibitijibibo** [comment] 2020-10-11 20:04
Going to assign this to @TheSpydog as it appears to be D3D11-specific. Traces are good, but we could _really_ use a full version - you can DM one of us in the FNA Discord if needed (or e-mail us, you can find our addresses in the commit logs).

**Comment by electroholic** [comment] 2020-10-11 20:10
I set it to HiDef in the game constructor.  Just tired it without this and no difference. I'll bung you my FNA build as it is right now (its a bit patchy as I'm changing quite a lot of things but you can play it through 100% just nothing saves right now and exit needs to be the escape key or alt - f4 - tbh all you need is to hit past the splash screen and you're into the post processing). I'll jump on the discord some time tomorrow (it's 50 MB so maybe a bit too big for my email server I think). you ok with just the compiled (xnb) content?

**Comment by flibitijibibo** [comment] 2020-10-11 20:11
Compiled data works for us - it's just easier to be able to trace and iterate on changes with a build we can run using modified FNA3D binaries.

**Comment by electroholic** [comment] 2020-10-11 20:13
cool. will sort out a zip archive to you tomorrow then.

**Comment by flibitijibibo** [comment] 2020-10-13 06:29
Fixed by https://github.com/FNA-XNA/FNA3D/commit/4e5ef6dcb665ec61ee38d237cf6a14a9085e03c6

**Closed by flibitijibibo** 2020-10-13 06:29 UTC
